# Welcome to Jekyll!
title: ikesau
description: >-
  website happy
baseurl: ""
url: "https://ikesau.co"
twitter_username: ikeasu
github_username: ikesau
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
